### ISSUE TITLE
Updating search page to include autocomplete

### ISSUE THREAD

**Issue by panosp17** [FutureNorthants/northants-website#165]
**Description**
Frontend modifications to plug the other two bits into each other appropriately.

**Acceptance criteria**
Autocomplete looks and works as expected.

**Time estimate**
2 days

**Comment by RichardBeards** [comment]
On microsoft edge, if you start to type in the search - at the bottom of the predictive text box the border line in cut off.
![image](https://user-images.githubusercontent.com/86593916/143599813-eff5fd77-f304-4610-a65a-dc820ecacc1f.png)

**Comment by RichardBeards** [comment]
On a mobile, when searching anything starting with the letters "no" the predictive text box is quite thin - the words "northamptonshire" then go outside the border.

**Comment by RichardBeards** [comment]
Search button is square rather than rounded, like on current live.

**Comment by DamienBurkeWN** [comment]
Fixed on staging, closing.
