### ISSUE TITLE
Scheduling pages

### ISSUE THREAD

**Issue by WestNorthantsRob** [FutureNorthants/northants-website#166]
**Frontend or Backend**: Frontend / Backend / Both

**Description**
Scheduling pages does not appear to be working:
When scheduling a new page it does not Publish
When scheduling an amendment to a page to publish at a certain time it does not Publish

**How to reproduce**
Create page (or amend content). Set publishing time in the Scheduling Options tab on the right hand side , save and close.
If the page is set to draft it does not publish. 
If the page is set to Publish it publishes immediately, not when scheduled

If we are doing something wrong can someone please provide us with instructions.

**Comment by DamienBurkeWN** [comment]
@WestNorthantsRob You're doing it right by saving as draft with scheduled date/time. The cron job that deals with scheduled publication (and much other stuff) runs every 20 minutes so if you're testing by scheduling a page to be published a few minutes from now, it could take 20 minutes for it to notice... and if you've already scheduled it to be unpublished a few minutes after publication, by the time the cron arrives it might skip the publication skip entirely as a result.

If you go to /admin/config/system/cron on one of the CMS staging sites you can see when the cron was last run - and kick it off early yourself if you want.

**Comment by WestNorthantsRob** [comment]
Thanks for the update
