### ISSUE TITLE
Accessibility issue - Colour differentiation

### ISSUE THREAD

**Issue by WestNorthantsRob** [FutureNorthants/northants-website#169]
**Frontend or Backend**: Frontend / Backend / Both

The Shaw Trust have picked up just one accessibility issue that will need developer intervention on their second Test. This only applies to the North site.

On the News pages, the date is still grey. Can this be made that same as the West site so there is a greater colour differentiation.

Examples:
North: https://www.northnorthants.gov.uk/news/consultation-launches-electric-vehicle-charging-points-across-north-northamptonshire
West: https://www.westnorthants.gov.uk/news/conditional-offer-sixfields-land-passes-rigorous-analysis

**Comment by AnthonyTaylor** [comment]
This is a design system issue and can be fixed by changing dark to darkest in this file: src/library/structure/NewsArticleDate/NewsArticleDate.styles.js

No change needs to be made in the underlying css.

I'll do this on Monday Morning.
