### ISSUE TITLE
Access Tab on Page creation

### ISSUE THREAD

**Issue by WestNorthantsRob** [FutureNorthants/northants-website#186]
**Frontend or Backend**: Frontend / Backend / Both

Something has changed as it was a mandatory requirement for us to tick a box in the Access tab when creating a new page (News items are an exception). This is so pages are assigned to a service ready for when/if we train up authors from services to edit their content. 

Can this functionality please be restored. as it is easy to miss.

**How to reproduce**
Create a page without ticking a box in the Access Tab and save

**Comment by DamienBurkeWN** [comment]
There have been no changes made related to this that I'm aware of. The **service area** field is not marked as required on any content types. To make it mandatory, in Drupal go to  **Structure | Content types | whatever | Manage fields**, scroll down to find the **service area** field, click the Edit button next it and tick the _Required_ box and save. Repeat for each content type that needs this.

**Comment by WestNorthantsRob** [comment]
Thanks Damien – I have made the necessary changes
