### ISSUE TITLE
Drupal 9.2.9. upgrade - Cosmetic

### ISSUE THREAD

**Issue by WestNorthantsRob** [FutureNorthants/northants-website#187]
Search dropbox on Mobile  is a little thin, it doesn't fit the width of the search box. If you start typing "no" the text goes outside the border

Search button seems to have changed shape - from rounded to square edges

**Comment by DamienBurkeWN** [comment]
Design System issue. Will be fixed by https://github.com/FutureNorthants/northants-design-system/pull/76

**Comment by DamienBurkeWN** [comment]
Now fixed on staging so I'll close this - reopen if you find anything new.
