### ISSUE TITLE
Drupal 9.2.9. upgrade  - Other

### ISSUE THREAD

**Issue by WestNorthantsRob** [FutureNorthants/northants-website#188]
Search suggestions not working from the top search bar on the news homepage

Images for News/ press releases are not displaying on the homepage or News page... also they are not displaying in the Media library in the backend 

Unable to download existing documents -  when clicked link takes you to the back end page saying The requested page could not be found. Try to download any document from https://staging.westnorthants.gov.uk/elections-and-voting/election-notices 

I have uploaded a new document and that works as expected.

**Comment by DamienBurkeWN** [comment]
As per Slack the images/docs is down to the files not being there as the staging platform doesn't use the same filesystem and is months out of date.

Search suggestions fixed on staging now. I'll close this but reopen it if you find anything new.
