### ISSUE TITLE
STAS-F02: Empty Button

### ISSUE THREAD

**Issue by willwise** [FutureNorthants/northants-website#2]
**Frontend or Backend**: Frontend

**Description**
When navigating to a button, descriptive text must be presented to screen reader users to indicate the function of the button.
Providing descriptive button labelling will allow users to make an informed decision whether to activate a button or not.

**How to reproduce**
- On the ‘search’ page there is an empty button on the ‘hotjar’ pop up box.
- On the 'Bin collection day' page, there is an incorrectly labelled button which appears to be unlabelled.

**Comment by willwise** [comment]
I believe that these buttons were only on there due to hotjar

**Comment by josielewis-warren** [comment]
@willwise check that the final bullet has been completed and if so this is done. the hotjar issue is listed as an external problem

**Comment by willwise** [comment]
@josielewis-warren both these buttons seem to be hotjar

**Comment by AnthonyTaylor** [comment]
Closing this as it is HotJar and out of our control
