### ISSUE TITLE
CMS - table need to include table scope

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#21]
**Frontend or Backend**: Frontend / Backend / Both

**Description**

In the CMS if a table is created, it correctly identifies and tags the hearer as a `<th>` However, it also needs to include the Table scope `<th scope="col">`

**How to reproduce**

I went in and manually changed these, but I have noticed that the scope = "col" has been stripped back out when the page has been saved

**Additional context**

**Comment by willwise** [comment]
@josielewis-warren I've had a look at this and its a little confusing as it seems to be there?
`<table>
<thead>
	<tr>
		<th scope="col">h</th>
		<th scope="col">h</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td>1</td>
		<td>1</td>
	</tr>
	<tr>
		<td>11</td>
		<td>11</td>
	</tr>
</tbody>
</table>`

**Comment by WestNorthantsRob** [comment]
Is there any movement on this?

When the page is first created the <th scope="col"> is there. However when a page saved and published the scope="col" is stripped out and can be seen below. Example url https://www.westnorthants.gov.uk/finance/contracts-register 
	<thead>
		<tr>
			<th>Value</th>
			<th>Procurement Process</th>
		</tr>
	</thead>

This is an accessibility issue and needs fixing.

**Comment by willwise** [comment]
Time taken
to do - 30 mins
to test - 15 mins
