### ISSUE TITLE
Component - News

### ISSUE THREAD

**Issue by richardhatdesson** [FutureNorthants/northants-website#26]
**Acceptance Criteria**
Given I am a Comms
When I add/edit a memorial
Then I can select up to three news articles (internal)

Given I am a website visitor
When I see a memorial
Then I can see three news articles each with and image, title and summary

**Technical notes**
None

**Design notes**
None

**Testing notes**
None

**Migrated from Jira**
https://deeson.atlassian.net/secure/RapidBoard.jspa?rapidView=423&projectKey=NOR&modal=detail&selectedIssue=NOR-180

**Comment by willwise** [comment]
This looks like its been already completed? @amyhaslam @richardhatdesson do either of you know whats going on with this?

**Comment by josielewis-warren** [comment]
@willwise check the permissions on this one please

**Comment by markpdeeson** [comment]
The backend work was completed / merged here:  https://github.com/FutureNorthants/northants-website/pull/36
