### ISSUE TITLE
Description needs adding in Metadata for News Landing Pages

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#43]
**Frontend or Backend**: Frontend / Backend / Both

**Description**

Description needs adding in Metadata for News Landing Pages: "Latest news from West Northamptonshire Council" "Latest news from North Northamptonshire Council"

**How to reproduce**

**Additional context**

Originally reported by Robert on the bug tracker 15/04/21 
Update 14/06/21: "I believe Lee fixed this but it is not yet showing on the live site"

**Comment by josielewis-warren** [comment]
@markpdeeson are you able to check the status on this one, please? We have some confusion around if this has been fixed?

**Comment by deesonlee** [comment]
Hi @josielewis-warren This was deployed in the last big deployment of work, I've checked both websites again and it shows when inspecting the source code
