### ISSUE TITLE
Unable to upload csv files

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#44]
**Frontend or Backend**: Frontend / Backend / Both

**Description**

Unable to upload csv files. We have to be able to upload csv files for Transparency Policy

**How to reproduce**

**Additional context**

Originally part of the bug tracker sheet raised by Robert 26/05/21
Update 14/06/21 - "This has been fixed and checked in testing two weeks ago but has not be rolled out to live"

Related slack convo: 
![image](https://user-images.githubusercontent.com/82222237/122553723-f48f3b80-d02f-11eb-948c-cd11ec10bf61.png)

![image](https://user-images.githubusercontent.com/82222237/122554192-931b9c80-d030-11eb-92e4-f292bfa17a8b.png)

**Comment by josielewis-warren** [comment]
@markpdeeson are you able to check the status on this one, please? looks like it got deployed 14/06 but Robert is saying it's not in live?

**Comment by deesonlee** [comment]
Hi @josielewis-warren This has been deployed and I'm seeing CSV files uploaded within Drupal
