### ISSUE TITLE
Exclude "Homepage" content type from XMLSitemap config

### ISSUE THREAD

**Issue by deesonlee** [FutureNorthants/northants-website#45]
**Frontend or Backend**:  Backend

**Description**
The "Homepage" content types should be excluded from the XMLSitemap generation.

**Additional context**
This should be a simple XMLSitemap config change within Drupal and then the config changes exported into a pull request for preprod_backend.

After this is deployed the cloudflare cache of the sitemap.xml file should be purged.

**Comment by AnthonyTaylor** [comment]
This issue was found when the following pages returned errors when they should not be discoverable.

- https://www.westnorthants.gov.uk/node/30
- https://www.northnorthants.gov.uk/node/40
