### ISSUE TITLE
Solr search docker image incompatibility (local dev)

### ISSUE THREAD

**Issue by markpdeeson** [FutureNorthants/northants-website#54]
The wodby/solr docker image is not compatible with M1 / arm64 Macbooks.

This means Solr-based functionality cannot be tested or developed on those devices, e.g. /news

We need to investigate and switch to an alternative docker image which offers compatibility with arm64 devices.

**Comment by markpdeeson** [comment]
Steps to switch:
1. Delete backend docker containers
2. edit .env and replace the SOLR_TAG with the same line from .env.example
3. Run make
4. Visit Configuration > Search and Metadata > Search API, Click the **Main** server in the table, and edit. Change the Solr core to **core1** 
5. View the News and Service indexes in the table, clear all indexed data then click Index now button to re-index.

**Comment by AnthonyTaylor** [comment]
This works for me now, thank you
