### ISSUE TITLE
Scroll bar to be removed from tables

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#58]
**Frontend or Backend**: Design System 

**Description**

Scroll bar to be removed from tables as they do not scroll and it is causing confusion
**How to reproduce**

https://www.westnorthants.gov.uk/business-and-licensing/additional-restrictions-grant-arg
**Additional context**

![image](https://user-images.githubusercontent.com/82222237/123668714-48b9cd00-d833-11eb-9219-5f7d4218ffea.png)

**Comment by josielewis-warren** [comment]
Rasied by Robert Walker 23/06/21

**Comment by josielewis-warren** [comment]
Investigation - 2hrs
Work - 2hr - 12hrs
Test - 0.5hr
**4.5-16.5hrs**

**Comment by DamienBurkeWN** [comment]
Closing as no longer appears to be relevant
