### ISSUE TITLE
Postcode checker doesn't cater for multiple sovereign areas

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#64]
**Frontend or Backend**:  Design system

**Description**

The handling of the postcode checker on both NNC/WNC websites isn't catering for postcodes which span multiple sovereign areas.
**How to reproduce**

Example postcode **NN2 8SB**

All but one property in this postcode is in Northampton, one is in Daventry. The postcode checker on the website reports that this postcode exists entirely within Daventry: 
[Bin collection day | West Northamptonshire Council (westnorthants.gov.uk) ](https://www.westnorthants.gov.uk/bins-recycling-and-street-cleaning/bin-collection-day)

The issue is in the handling of the response from the postcode finder API, which is returning the correct data :
https://api.westnorthants.digital/check-postcode/nn28sb 

Where the returning payload has numOfSovereign greater than one then a dropdown list should appear to allow the customer to select the individual property so we can route correctly.

**Additional context**

Logged by Kevin White (via email to WNC Digital)

**Comment by willwise** [comment]
https://github.com/FutureNorthants/northants-design-system/tree/new_postcode_checker
This might be worth a look for whoever picks this up

**Comment by AnthonyTaylor** [comment]
Investigation - 6hrs - 12hrs
Work - 6hrs- 18hrs
Test - 1hr
12hrs - 31hrs
