### ISSUE TITLE
Memorial Homepage accessibility 

### ISSUE THREAD

**Issue by AnthonyTaylor** [FutureNorthants/northants-website#82]
**Frontend or Backend**: Frontend 

**Description**
duplicate #all-services on memorial themed homepage

**How to reproduce**
https://validator.w3.org/nu/?doc=https%3A%2F%2Fstaging.westnorthants.gov.uk%2F

**Additional context**
To be looked at after all other memorial changes have been made (#33 Memorial handling of homepage)

**Comment by WestNorthantsRob** [comment]
@willwise @AnthonyTaylor I've just noticed that there is no H1 on the Memorial page, can this be looked at, thanks
