### ISSUE TITLE
Comms editors to create short URLs

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#95]
**Description**

If it is possible to give access to Comms editors access to create short URLs without giving them being able to see the whole of the Site Config area.
**Example**

*Originally requested by Robert Walker via email 21/06/21

**Comment by DamienBurkeWN** [comment]
@WestNorthantsRob yes, you can edit the Comms user role: go to **People | Roles | Comms | Edit permissions **
Search for 'URL alias' on that page and you'll see you can tick **Create and edit URL aliases**, if ticked this gives them control over the URL alias in any individual news articles they create or edit.

**Comment by WestNorthantsRob** [comment]
Thanks Damien
